language: node_js
node_js:
 - 0.10
#addons:
#  firefox: "38.7.1esr"
#env: DISPLAY=:99.0
services:
 - redis-server
before_install:
 - sudo apt-get update && sudo apt-get install -qq build-essential libssl-dev curl
 - cp conf.json.example conf.json
# - sh -e /etc/init.d/xvfb start
#before_script:
# - curl -L https://selenium-release.storage.googleapis.com/2.53/selenium-server-standalone-2.53.0.jar > bin/selenium-server-standalone.jar
script: "npm run noseleniumtest"
